class Produto:
    def __init__(self, nome, preco):
        self.nome = nome
        self.preco = preco
    def __repr__(self):
        return "Nome: "+self.nome+", Preco: "+str(self.preco)

if __name__ == '__main__':
    produtos = []
    produtos.append(Produto("Big Mac",3.99))
    produtos.append(Produto("2 Cheeseburgers",2.58))
    produtos.append(Produto("Quarter Pounder with Cheese",3.79))
    produtos.append(Produto("Double Quarter Pounder with Cheese",4.79))
    produtos.append(Produto("Deluxe Quarter Pounder",4.19))
    produtos.append(Produto("Lettuce & Tomato Sirloin Third Pound Burger",5.00))
    produtos.append(Produto("Bacon & Cheese Sirloin Third Pound Burger",5.30))
    produtos.append(Produto("Steakhouse Sirloin Third Pound Burger",5.10))
    produtos.append(Produto("Premium McWrap Chicken & Bacon",4.19))
    produtos.append(Produto("Premium McWrap Sweet Chili Chicken",4.19))
    produtos.append(Produto("Filet-O-Fish",3.79))
    produtos.append(Produto("Double Filet-O-Fish",4.79))
    produtos.append(Produto("Artisan Grilled Chicken",4.19))
    produtos.append(Produto("Crispy Chicken Deluxe",4.19))
    produtos.append(Produto("Southern Style Chicken",3.89))
    produtos.append(Produto("Bacon Clubhouse Burger",4.49))
    produtos.append(Produto("Premium Chicken Bacon Clubhouse",4.49,))
    produtos.append(Produto("McChicken",3.79))
    produtos.append(Produto("Chicken McNuggets",4.49))
    produtos.append(Produto("Chicken Select Tenders",2.99))
    produtos.append(Produto("Southwest Salad",4.79))
    produtos.append(Produto("Bacon Ranch Salad",4.59))
    produtos.append(Produto("Mac Snack Wrap",1.69))
    produtos.append(Produto("Chicken Snack Wrap",1.69))
    produtos.append(Produto("French Fries",1.29))
    produtos.append(Produto("Grilled Onion Cheddar Burger",1.00))
    produtos.append(Produto("McDouble",1.39))
    produtos.append(Produto("Bacon Cheddar McChicken",2.00))
    produtos.append(Produto("Buffalo Ranch McChicken",1.00))
    produtos.append(Produto("Bacon Buffalo Ranch McChicken",2.00))
    produtos.append(Produto("BBQ Ranch Burger",1.00))
    produtos.append(Produto("Cheeseburger",1.00))
    produtos.append(Produto("Double Cheeseburger",1.59))
    produtos.append(Produto("Triple Cheeseburger",2.29))
    produtos.append(Produto("Daily Double",1.99))
    produtos.append(Produto("Jalapeño Double",2.00))
    produtos.append(Produto("Bacon McDouble",2.00))
    produtos.append(Produto("Parfait",1.00))
    produtos.append(Produto("Side Salad",1.59))
    produtos.append(Produto("3 Cookies",1.00))
    produtos.append(Produto("Apple Slices",1.00))
    produtos.append(Produto("Sausage McMuffin",1.19))
    produtos.append(Produto("Sausage Biscuit",1.19))
    produtos.append(Produto("Hash Browns",1.00))
    produtos.append(Produto("Coffee",0.90))
    produtos.append(Produto("Egg & Cheese Biscuit",1.29))
    produtos.append(Produto("Cinnamon Melt",1.59))
    produtos.append(Produto("Smoothie Small",2.39))
    produtos.append(Produto("Frappe Small",2.39))
    produtos.append(Produto("Frozen Strawberry Lemonade",2.39))
    produtos.append(Produto("Espresso & Chocolate",2.39))
    produtos.append(Produto("Premium Roast Coffee",0.90))
    produtos.append(Produto("Iced Coffee",1.59))
    produtos.append(Produto("Sweet Tea",1.00))
    produtos.append(Produto("Soft Drink",1.00))
    produtos.append(Produto("Orange Juice",1.59))
    produtos.append(Produto("Milk",1.00))
    produtos.append(Produto("Dasani Water",1.00))
    produtos.append(Produto("Shake",2.19))
    produtos.append(Produto("Apple Pie",0.89))
    produtos.append(Produto("Cone",1.00))
    produtos.append(Produto("McFlurry",1.79))
    produtos.append(Produto("Soft Baked Chocolate Chip",0.39))
    produtos.append(Produto("Strawberry & Creme",0.89))
    produtos.append(Produto("Chocolate Chip Cookie Tote",3.99))
    produtos.append(Produto("Egg White Delight McMuffin",2.79))
    produtos.append(Produto("Egg McMuffin",2.79))
    produtos.append(Produto("Sausage McMuffin with Egg",2.99))
    produtos.append(Produto("Cheese Biscuit",3.19))
    produtos.append(Produto("Sausage Biscuit with Egg",2.79))
    produtos.append(Produto("Sausage Gravy & Biscuit",2.69))
    produtos.append(Produto("Sausage McGriddles",2.79))
    produtos.append(Produto("Sausage Burrito",1.19))
    produtos.append(Produto("Big Breakfast with Hot Cakes",5.29))
    produtos.append(Produto("Big Breakfast",3.49))
    produtos.append(Produto("Hot Cakes with Sausage",2.99))
    
    arquivo = open('dados/produtos.txt', 'w',encoding="utf8")
    linhas = 0
    for produto in produtos:
        if linhas < len(produtos)-1:
            arquivo.write(produto.nome + "|" +str(produto.preco)+"\n")
        if linhas == len(produtos)-1:
            arquivo.write(produto.nome + "|" +str(produto.preco))
        linhas = linhas + 1
    arquivo.close()
    print("produtos salvos")
    

